### ISSUE TITLE
Recommendations for how to use this in an application without impacting production

### ISSUE THREAD

**Issue by lpil** [aosasona/dotenv#17]
Hello! Thanks for this library.

Adding this to my programs main function works great in development, but in production it causes the application to fail to run as the dotenv file is not present.

Do you have any advice for how to work around this problem?

Thanks,
Louis

**Comment by aosasona** [comment]
Hi Louis!
I have been wanting to rewrite this but I have not had the time, but in the mean time, I will try to help get this sorted, ideally it should ignore the errors and simply not load the file, any chance I could see the error you are getting?

**Comment by aosasona** [comment]
![CleanShot 2024-04-04 at 00 20 58@2x](https://github.com/aosasona/dotenv/assets/97124713/d7e20d26-c920-4c64-bd52-bb9810a73f0e)
I went back to confirm and the app I did make this for and others I have used it in do not have a .env file, I use Fly Secrets and it hasn't caused a crash, I'm curious to see what I might have broken in the last update.

**Comment by lpil** [comment]
Oh sorry! This is my mistake, you are completely right and I had got muddled up in my late-night coding. Please ignore me 🙏
