### ISSUE TITLE
No windows support?

### ISSUE THREAD

**Issue by Iapetus-11** [aosasona/dotenv#29]
On my m1 mac, dotenv recognizes & loads variables from `.env` files, but on windows I've had no luck with the same project.

Here's what my .env looks like:
```
SECRET_KEY=abc123
DATABASE_URL=abc123
```

And here's what my code looks like:
```gleam
import dot_env
import dot_env/env

dot_env.new()
|> dot_env.set_path(".env")
|> dot_env.set_debug(False)
|> dot_env.load()

let assert Ok(secret_key) = env.get_string("SECRET_KEY")
let assert Ok(database_url) = env.get_string("DATABASE_URL")
```

And here's the error I'm getting:
```
runtime error: let assert

Pattern match failed, no pattern matched the value.

unmatched value:
  Error("key SECRET_KEY is not set")
```

**Comment by aosasona** [comment]
Hi there! Thanks for reporting this. 

I haven't tested on Windows and I can't spin up a VM and set it up right now to reproduce this. But, my best guess would be something to do with the file path, could you try enabling debug mode and also setting `ignore_missing_file` to false so that it returns an error if it doesn't exist.

**Comment by Iapetus-11** [comment]
I enabled those settings and ran my code again with the following output:

```gleam
dot_env.new()
|> dot_env.set_path(".env")
|> dot_env.set_debug(True)
|> dot_env.set_ignore_missing_file(False)
|> dot_env.load()
```

```
unclosed double quote
runtime error: let assert

Pattern match failed, no pattern matched the value.

unmatched value:
  Error("key SECRET_KEY is not set")
```

It seems like it's screaming about an unclosed double quote? My `.env` doesn't have any quotes or double quotes so maybe it's something to do with loading the file based off the path?

Anyways, since you can't test on Windows, I'd be happy to be a guinea pig so just let me know if there's anything I can do!

**Comment by aosasona** [comment]
I think I know where that error is from specifically but I am unsure why, looks like an empty value (which shouldn't have that error either; so, a bug), I will have boot into a VM later today to try to figure this out. I hope it is not urgent, sorry for the trouble!

**Comment by Iapetus-11** [comment]
I'm not using wsl2 just using powershell via the terminal app. 

As for reproduction, I've actually just been testing with `abc123`, these are the exact file contents I've been testing with haha:
```
SECRET_KEY=abc123
DATABASE_URL=abc123
```

Also, not urgent at all please don't rush!

**Comment by aosasona** [comment]
![CleanShot 2024-09-23 at 00 15 42](https://github.com/user-attachments/assets/e42d718a-805b-4e67-bba6-2fee4592cc0e)
I have been able to identify the issue; `string.to_graphemes` apparently does not split `\r\n` to `["\r", "\n"]` on Windows as initially assumed and I have opted for unifying all line endings instead (a very slight perf hit but nothing noticeable in the end).

The fix will be available for you to test in the next release!

**Comment by aosasona** [comment]
Please give the latest release (https://github.com/aosasona/dotenv/releases/tag/1.2.0) a go when you can and let me know if that fixed it!

**Comment by Iapetus-11** [comment]
Sorry for the late response. I finally got around to testing it and and it works perfectly!

Thank you so much :)
